import type { NextPage } from "next";
import Head from "next/head";
import { FormEvent, useState } from "react";
import { date } from "zod";


function romanize(num: any) {
  const lookup: any = {M:1000,CM:900,D:500,CD:400,C:100,XC:90,L:50,XL:40,X:10,IX:9,V:5,IV:4,I:1};
  let roman = '',i;
  for ( i in lookup ) {
    while ( num >= lookup[i] ) {
      roman += i;
      num -= lookup[i];
    }
  }
  return roman;
}

const Home: NextPage = () => {
  const [command, setCommand] = useState<string | undefined>();
  const handleSubmit = async (event: FormEvent) => {
    // Stop the form from submitting and refreshing the page.
    event.preventDefault();

    // Cast the event target to an html form
    const form = event.target as HTMLFormElement;

    // Get data from the form.
    const data = {
      command: form.terminal.value as number,
    };
    
    setCommand(romanize(data.command));
  };

  return (
    <>
      <Head>
        <title>Number To Roman Numeral</title>
        <meta name="description" content="Generated by Justin Bender" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-marble mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          Turn a <span className="bg-clip-text text-transparent bg-gradient-to-b from-yellow-400 to-yellow-300 hover:motion-safe:animate-pulse">Number</span> into a <span className="bg-clip-text text-transparent bg-gradient-to-t from-yellow-400 to-yellow-300 hover:motion-safe:animate-pulse">Roman Numeral</span>
        </h1>
        <div className="flex flex-col mt-2 pt-2">
        {command && 
          <p className="text-5xl md:text-[5rem] font-extrabold text-gray-500 text-center break-all">
            {command}
          </p>
        }
          <form onSubmit={handleSubmit}>
            <label htmlFor="terminal" hidden>
              Number to Numeral
            </label>
            <input
              type="number"
              id="terminal"
              name="terminal"
              placeholder="Enter a number"
              className="bg-zinc-200 text-zinc-800 min-w-[100%] focus:outline-yellow-500 p-3 text-center"
              required
              autoComplete="off"
              maxLength={50}
            />
            <span
              className={
                "group rounded-xl outline-none text-white disabled:opacity-40 ml-3 mt-5 bg-indigo-800"
              }>
            <button className="min-w-[100%] px-3 mx-auto mb-1 mr-[0.8px] ml-[0.8px] text-xl tracking-tight uppercase text-center italic rounded-xl border-2 font-normal py-3 flex flex-row items-center justify-center border-yellow-700 hover:border-yellow-600 bg-yellow-500 hover:shadow-inner hover:shadow-4xl hover:shadow-zinc-800/80" type="submit">
              Convert
            </button>
            </span>
          </form>
        </div>
      </main>
    </>
  );
};

export default Home;
